### ISSUE TITLE
Add extra note so import works in CLI?

### ISSUE THREAD

**Issue by ckesurf** [learn-co-curriculum/python-p3-defining-object-inheritance#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195249?module_item_id=439034

### Concern

If the student executes the lines as they are [here](https://github.com/learn-co-curriculum/python-p3-defining-object-inheritance/blob/main/README.md?plain=1#L182-L183):

<img width="964" alt="Screen Shot 2022-12-12 at 1 33 17 PM" src="https://user-images.githubusercontent.com/1832658/207126202-fc532ca5-6865-4066-867d-168bbb640e54.png">

Then the student will ultimately runs into this error:
<img width="1422" alt="Screen Shot 2022-12-12 at 1 34 58 PM" src="https://user-images.githubusercontent.com/1832658/207126525-b50e48a6-74c5-46c5-accd-097da344e540.png">

### Suggested Changes

However this can be fixed by adding a `lib.` to the [import on Line 1 in car.py](https://github.com/learn-co-curriculum/python-p3-defining-object-inheritance/blob/main/lib/car.py#L1). Worth either changing the source code or adding a note to the student to make that edit?

**Comment by professor-ben** [comment]
Fixed- thanks!
