### ISSUE TITLE
self

### ISSUE THREAD

**Issue by DavidWolff218** [learn-co-curriculum/python-p3-defining-object-inheritance#4]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195249?module_item_id=439034

### Concern

I made the assumption in this lab that the car class doesn't need to bring in 'self' as an argument because that is happening in the parent class, but it may be worth making note of that in the material.

**Comment by pgill97** [comment]
@DavidWolff218 Can you give us a specific example of which self argument you are talking about?
